#!/bin/bash
# Initialize server.properties
touch server.properties
echo "" > server.properties

# Write header
echo "# Minecraft server properties \n" >> server.properties
echo "# Autogenerated by Docker \n" >> server.properties

# Write props
echo "spawn-protection=${MC_SPAWN_PROTECTION}\n" >> server.properties
echo "max-tick-time=${MC_MAX_TICK_TIME}\n" >> server.properties
echo "generator-settings=${MC_GENERATOR_SETTINGS}\n" >> server.properties
echo "gamemode=${MC_GAMEMODE}\n" >> server.properties
echo "force-gamemode=${MC_FORCE_GAMEMODE}\n" >> server.properties
echo "hardcore=${MC_HARDCORE}\n" >> server.properties
echo "allow-nether=${MC_ALLOW_NETHER}\n" >> server.properties
echo "player-idle-timeout=${MC_PLAYER_IDLE_TIMEOUT}\n" >> server.properties
echo "difficulty=${MC_DIFFICULTY}\n" >> server.properties
echo "spawn-animals=${MC_SPAWN_ANIMALS}\n" >> server.properties
echo "spawn-npcs=${MC_SPAWN_NPCS}\n" >> server.properties
echo "spawn-monsters=${MC_SPAWN_MONSTERS}\n" >> server.properties
echo "generate-structures=${MC_GENERATE_STRUCTURES}\n" >> server.properties
echo "op-permission-level=${MC_OPS_PERMISSION_LEVEL}\n" >> server.properties
echo "broadcast-console-to-ops=${MC_OPS_BROADCAST_CONSOLE}\n" >> server.properties
echo "announce-player-achievements=${MC_ANNOUNCE_PLAYER_ACHIEVEMENTS}\n" >> server.properties
echo "pvp=${MC_PVP}\n" >> server.properties
echo "enable-command-block=${MC_COMMAND_BLOCK_ENABLED}\n" >> server.properties
echo "max-players=${MC_MAX_PLAYERS}\n" >> server.properties
echo "network-compression-threshold=${MC_NETWORK_COMPRESSION_THRESHOLD}\n" >> server.properties
echo "level-seed=${MC_LEVEL_SEED}\n" >> server.properties
echo "level-type=${MC_LEVEL_TYPE}\n" >> server.properties
echo "max-world-size=${MC_MAX_WORLD_SIZE}\n" >> server.properties
echo "server-ip=${MC_SERVER_IP}\n" >> server.properties
echo "server-port=${MC_SERVER_PORT}\n" >> server.properties
echo "allow-flight=${MC_ALLOW_FLIGHT}\n" >> server.properties
echo "level-name=${MC_WORLD_NAME}\n" >> server.properties
echo "view-distance=${MC_VIEW_DISTANCE}\n" >> server.properties
echo "resource-pack=${MC_RESOURCE_PACK}\n" >> server.properties
echo "resource-pack-sha1=${MC_RESOURCE_PACK_SHA1}\n" >> server.properties
echo "white-list=${MC_WHITELIST}\n" >> server.properties
echo "online-mode=${MC_ONLINE_MODE}\n" >> server.properties
echo "max-build-height=${MC_MAX_BUILD_HEIGHT}\n" >> server.properties
echo "use-native-transport=${MC_USE_NATIVE_TRANSPORT}\n" >> server.properties
echo "motd=${MC_MOTD}\n" >> server.properties
echo "snooper-enabled=${MC_SNOOPER_ENABLED}\n" >> server.properties
echo "enable-query=${MC_ENABLE_QUERY}\n" >> server.properties
echo "enable-rcon=${MC_ENABLE_RCON}\n" >> server.properties
