#!/bin/bash
# Initialize server.properties
touch server.properties
echo "" > server.properties

# Write header
echo "# Minecraft server properties \n" >> server.properties
echo "# Autogenerated by Docker \n" >> server.properties

# Write props
if [ -z ${MC_SPAWN_PROTECTION} ]; then
	echo "spawn-protection=${MC_SPAWN_PROTECTION}\n" >> server.properties
fi

if [ -z ${MC_MAX_TICK_TIME} ]; then
	echo "max-tick-time=${MC_MAX_TICK_TIME}\n" >> server.properties
fi

if [ -z ${MC_GENERATOR_SETTINGS} ]; then
	echo "generator-settings=${MC_GENERATOR_SETTINGS}\n" >> server.properties
fi

if [ -z ${MC_GAMEMODE} ]; then
	echo "gamemode=${MC_GAMEMODE}\n" >> server.properties
fi

if [ -z ${MC_FORCE_GAMEMODE} ]; then
	echo "force-gamemode=${MC_FORCE_GAMEMODE}\n" >> server.properties
fi

if [ -z ${MC_HARDCORE} ]; then
	echo "hardcore=${MC_HARDCORE}\n" >> server.properties
fi

if [ -z ${MC_ALLOW_NETHER} ]; then
	echo "allow-nether=${MC_ALLOW_NETHER}\n" >> server.properties
fi

if [ -z ${MC_PLAYER_IDLE_TIMEOUT} ]; then
	echo "player-idle-timeout=${MC_PLAYER_IDLE_TIMEOUT}\n" >> server.properties
fi

if [ -z ${MC_DIFFICULTY} ]; then
	echo "difficulty=${MC_DIFFICULTY}\n" >> server.properties
fi

if [ -z ${MC_SPAWN_ANIMALS} ]; then
	echo "spawn-animals=${MC_SPAWN_ANIMALS}\n" >> server.properties
fi

if [ -z ${MC_SPAWN_NPCS} ]; then
	echo "spawn-npcs=${MC_SPAWN_NPCS}\n" >> server.properties
fi

if [ -z ${MC_SPAWN_MONSTERS} ]; then
	echo "spawn-monsters=${MC_SPAWN_MONSTERS}\n" >> server.properties
fi

if [ -z ${MC_GENERATE_STRUCTURES} ]; then
	echo "generate-structures=${MC_GENERATE_STRUCTURES}\n" >> server.properties
fi

if [ -z ${MC_OPS_PERMISSION_LEVEL} ]; then
	echo "op-permission-level=${MC_OPS_PERMISSION_LEVEL}\n" >> server.properties
fi

if [ -z ${MC_OPS_BROADCAST_CONSOLE} ]; then
	echo "broadcast-console-to-ops=${MC_OPS_BROADCAST_CONSOLE}\n" >> server.properties
fi

if [ -z ${MC_ANNOUNCE_PLAYER_ACHIEVEMENTS} ]; then
	echo "announce-player-achievements=${MC_ANNOUNCE_PLAYER_ACHIEVEMENTS}\n" >> server.properties
fi

if [ -z ${MC_PVP} ]; then
	echo "pvp=${MC_PVP}\n" >> server.properties
fi

if [ -z ${MC_COMMAND_BLOCK_ENABLED} ]; then
	echo "enable-command-block=${MC_COMMAND_BLOCK_ENABLED}\n" >> server.properties
fi

if [ -z ${MC_MAX_PLAYERS} ]; then
	echo "max-players=${MC_MAX_PLAYERS}\n" >> server.properties
fi

if [ -z ${MC_NETWORK_COMPRESSION_THRESHOLD} ]; then
	echo "network-compression-threshold=${MC_NETWORK_COMPRESSION_THRESHOLD}\n" >> server.properties
fi

if [ -z ${MC_LEVEL_SEED} ]; then
	echo "level-seed=${MC_LEVEL_SEED}\n" >> server.properties
fi

if [ -z ${MC_LEVEL_TYPE} ]; then
	echo "level-type=${MC_LEVEL_TYPE}\n" >> server.properties
fi

if [ -z ${MC_MAX_WORLD_SIZE} ]; then
	echo "max-world-size=${MC_MAX_WORLD_SIZE}\n" >> server.properties
fi

if [ -z ${MC_SERVER_IP} ]; then
	echo "server-ip=${MC_SERVER_IP}\n" >> server.properties
fi

if [ -z ${MC_SERVER_PORT} ]; then
	echo "server-port=${MC_SERVER_PORT}\n" >> server.properties
fi

if [ -z ${MC_ALLOW_FLIGHT} ]; then
	echo "allow-flight=${MC_ALLOW_FLIGHT}\n" >> server.properties
fi

if [ -z ${MC_WORLD_NAME} ]; then
	echo "level-name=${MC_WORLD_NAME}\n" >> server.properties
fi

if [ -z ${MC_VIEW_DISTANCE} ]; then
	echo "view-distance=${MC_VIEW_DISTANCE}\n" >> server.properties
fi

if [ -z ${MC_RESOURCE_PACK} ]; then
	echo "resource-pack=${MC_RESOURCE_PACK}\n" >> server.properties
fi

if [ -z ${MC_RESOURCE_PACK_SHA1} ]; then
	echo "resource-pack-sha1=${MC_RESOURCE_PACK_SHA1}\n" >> server.properties
fi

if [ -z ${MC_WHITELIST} ]; then
	echo "white-list=${MC_WHITELIST}\n" >> server.properties
fi

if [ -z ${MC_ONLINE_MODE} ]; then
	echo "online-mode=${MC_ONLINE_MODE}\n" >> server.properties
fi

if [ -z ${MC_MAX_BUILD_HEIGHT} ]; then
	echo "max-build-height=${MC_MAX_BUILD_HEIGHT}\n" >> server.properties
fi

if [ -z ${MC_USE_NATIVE_TRANSPORT} ]; then
	echo "use-native-transport=${MC_USE_NATIVE_TRANSPORT}\n" >> server.properties
fi

if [ -z ${MC_MOTD} ]; then
	echo "motd=${MC_MOTD}\n" >> server.properties
fi

if [ -z ${MC_SNOOPER_ENABLED} ]; then
	echo "snooper-enabled=${MC_SNOOPER_ENABLED}\n" >> server.properties
fi

if [ -z ${MC_ENABLE_QUERY} ]; then
	echo "enable-query=${MC_ENABLE_QUERY}\n" >> server.properties
fi

if [ -z ${MC_ENABLE_RCON} ]; then
	echo "enable-rcon=${MC_ENABLE_RCON}\n" >> server.properties
fi
